### PR TITLE
Ci fixes

### PR DESCRIPTION
**Pull request by mathstuf**
---
Looks like nightly schedules would be nice to catch these kinds of things ahead of time.

Cc: @tomhoule

### CODE REVIEW

**Comment by tomhoule** [comment]
I haven't looked into it in detail (I'm in a bit of a rush today) but it looks like only the wasm and rustfmt builds are failing. We'll revisit the wasm/web support soon and we can look at rustfmt at the same time, so you don't have to fix it if you don't have the time. Should I merge?

**Comment by mathstuf** [comment]
It's the clippy checks that are failing. Will amend. The wasm failures can be more easily ignored for now.

**Comment by mathstuf** [comment]
I'll also note that there are better patterns for enforcing formatting of code (namely automatically fixing the problems instead of just informing). You can read some of the details on that process here:

  - CMake instructions using it: https://gitlab.kitware.com/cmake/cmake/blob/master/Help/dev/review.rst#id5
  - A project that will be migrating to it "soon": https://discourse.vtk.org/t/clang-format-discussion/2073

I'm working on a command line variant of it [here](https://gitlab.kitware.com/utils/rust-ghostflow/merge_requests/206) so that it can be used in GitHub Actions.

**Comment by tomhoule** [comment]
I'm very open to doing that in CI!

**Comment by mathstuf** [comment]
Woo! Green.

**Pull request merged**
