### PR TITLE
Rust 2018

### PR DESCRIPTION
**Pull request by h-michael**
https://rust-lang-nursery.github.io/edition-guide/editions/transitioning-an-existing-project-to-a-new-edition.html#writing-idiomatic-code-in-a-new-edition

after merge these PR, #194, #191.

### CODE REVIEW

**Comment by theduke** [comment]
In Juniper I think we'll wait until 1.33 with the 2018 edition refactor.

**Comment by tomhoule** [comment]
Since graphql-client-web has been merged I think we'll publish 0.6 very soon without the edition upgrade, and merge this PR for 0.7. Does that seem good?

**Comment by h-michael** [comment]
I think it seems to be fine.

**Comment by h-michael** [comment]
When publishing v0.6.0, I rebase to v0.7.0.

**Comment by tomhoule** [comment]
@h-michael  I think it's safe to transition to the 2018 edition in the next release, if you want to update this branch we can merge it. Otherwise I can work on it, so no pressure :)

**Comment by h-michael** [comment]
@tomhoule OK I'll fix it tonight :)

**Comment by h-michael** [comment]
@tomhoule I've finished :)

**Comment by h-michael** [comment]
```
error: couldn't read /home/travis/build/graphql-rust/graphql-client/target/debug/build/graphql_client-dd959f27fce7a953/out/skeptic-tests.rs: No such file or directory (os error 2)
 --> graphql_client/tests/skeptic.rs:1:1
  |
1 | include!(concat!(env!("OUT_DIR"), "/skeptic-tests.rs"));
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
:(

**Comment by tomhoule** [comment]
Weird! I restarted the build, let's see how it goes this time.

**Comment by scrogson** [comment]
Correct me if I'm wrong...I think the latest practice with `serde` is to include `serde` with `"derive"` features enabled, instead of including `serde_derive` directly?

**Comment by h-michael** [comment]
@tomhoule CI has passed :)

**Comment by tomhoule** [comment]
Sorry for the delay! I'll merge this properly this weekend.

**Comment by tomhoule** [comment]
Sorry for the delay, I'm merging this! Thanks a lot for the hard work!

**Pull request merged**
