### PR TITLE
Derive Debug for ResponseData and Variables

### LINKED ISSUE #248: Variables should impl Debug
I think `dbg!(&vars)` is very useful for debugging purposes.
Perhaps it should be introduced as variables_derives param on `graphql` procmacro?

### PR DESCRIPTION
**Pull request by MikailBag**
fixes #248

### CODE REVIEW

**Comment by tomhoule** [comment]
Thanks for the PR!

Adding Debug to variables is fine as a temporary workaround, but we already have the `response_derives` ResponseData and we don't want Debug by default there because it has a non-negligible effect on code size when targeting browsers. 

With that change we could merge this.

I'll try to implement the proper solution (`variable_derives`) for the next release.

**Comment by mathstuf** [comment]
Hmm. Looking at the code, `additional_derives` applies to variables and responses. Any reason not to just use that? Or should that be split to have `variable` and `response` specific halves?

**Comment by tomhoule** [comment]
@mathstuf  I haven't touched that code in such a long time that I don't remember what the current state is. I agree that variables and response derives should be separate - I'll try to make it happen for next release (soon™)

**Comment by tomhoule** [comment]
This should be addressed by https://github.com/graphql-rust/graphql-client/pull/285, which was just merged. Please open an issue if doesn't work for your use-case :)

**Pull request closed without merging**
