### PR TITLE
Prettier setup

### PR DESCRIPTION
**Pull request by maxymshg**

### CODE REVIEW

**Comment by maxymshg** [comment]
@h-michael , Thank you.

I looked over TravicCI docs for something like this, but not found anything except simple `apt install` to get nodejs.

**Comment by maxymshg** [comment]
@h-michael , Could you please share the link to the documentation where you find this info? I tried and it's failed for me.

**Comment by h-michael** [comment]
@maxymshg 
Sorry, my info seems to be old.
Now, your way seems to be right.
https://docs.travis-ci.com/user/customizing-the-build/#installing-a-second-programming-language

**Comment by h-michael** [comment]
@maxymshg 
Could you apply prettier to existing queries?

**Comment by h-michael** [comment]
You should update CONTRIBUTING.md with how to install prettier, how to apply prettier.

**Comment by maxymshg** [comment]
Ok, thank you. I'll update CONTRIBUTING.md soon.
> Could you apply prettier to existing queries?
I already run prettier over `.json`, `.graphql` files. What else I missed?

**Comment by h-michael** [comment]
It seems that CI failed because of returned exit 1 by prettier.

**Comment by maxymshg** [comment]
Yes, I think it's because of this: https://github.com/prettier/prettier/issues/4144#issuecomment-381526419

**Comment by maxymshg** [comment]
I've updated CONTRIBUTING.md. What we should do with this fail from prettier?

**Comment by maxymshg** [comment]
@h-michael or @tomhoule, Could you please assist with next steps?

**Comment by tomhoule** [comment]
Sorry for the late review! It's a very busy week. The current setup looks great, thanks for the PR! I think it fails as it should already. If you run prettier once with `--write` the build should pass, right?

**Comment by h-michael** [comment]
@maxymshg 
I create [PR](https://github.com/maxymshg/graphql-client/pull/1) to this branch.
After merging it, you can get exit status 0.

**Comment by maxymshg** [comment]
Thank you for support, PR merged.

**Comment by h-michael** [comment]
@tomhoule 
Now, pass the CI :tada: .

**Comment by h-michael** [comment]
@tomhoule 
Would you resolve conflicts?

**Comment by tomhoule** [comment]
@h-michael done, let's merge as soon as it passes CI.

**Pull request merged**
