### PR TITLE
Enum other variant for fragments

### PR DESCRIPTION
**Pull request by visd0m**
Reopen https://github.com/graphql-rust/graphql-client/pull/373 accidentally closed due to base branch rename from master to main

### CODE REVIEW

**Comment by visd0m** [comment]
@tomhoule this pr reopen the https://github.com/graphql-rust/graphql-client/pull/373

**Comment by tomhoule** [comment]
Thanks! I'll try to find time to review as soon as possible.

**Comment by visd0m** [comment]
@tomhoule what about this pr? If you don't have time to review it can you suggest me some other reviewer?

**Review by tomhoule — APPROVED** [review]
Sorry @visd0m , I indeed very rarely find time for graphql-client. The PR looks, good let's merge, thanks :+1:

For anyone else who might be reading, external reviews are very much appreciated.

**Pull request merged**
