### PR TITLE
Move the graphql_client crate to a subdirectory

### LINKED ISSUE #118: Move the graphql-client crate to a subdirectory
Big projects like diesel and juniper are already organized that way. It would make it clearer that the top-level is a workspace with multiple sub-crates. Any downsides to this?

### PR DESCRIPTION
**Pull request by panicbit**
Fixes #118

### CODE REVIEW

**Comment by tomhoule** [comment]
Thanks for the PR! CI is not passing however. There is a wrong path somewhere apparently.

**Comment by panicbit** [comment]
Wtf, all tests run fine on my machine D:

**Comment by panicbit** [comment]
Everything's green now :relaxed:

**Comment by tomhoule** [comment]
I merged another PR and now this needs rebasing, sorry :/ I want to do another full review since it's a big change but in principle it looks good.

**Comment by panicbit** [comment]
Rebased :bowtie:

**Comment by tomhoule** [comment]
Looks good, thanks for the big PR :)

**Pull request merged**
