### PR TITLE
Ci perf

### PR DESCRIPTION
**Pull request by mathstuf**
---
Builds on #280. See #281.

### CODE REVIEW

**Comment by mathstuf** [comment]
Heh. Looks like even the ["do more than it should" buildset](https://travis-ci.org/graphql-rust/graphql-client/builds/592379745) is about 5 minutes faster. Cutting out the excess 3 builds should help that (since we're a bit over the concurrency limit Travis allows right now).

However, I suspect that much more improvement could be done. Doing `rustfmt` on [this crate](https://github.com/mathstuf/rust-keyutils) is under 45 s. Granted, it is a much smaller project, but `cargo fmt` shouldn't be taking 8 minutes (most of this is in cache extraction/collection :/ ). I don't know how easy it'd be to run the WASM tests in a Cirrus CI pipeline (probably not too bad), but since the matrix isn't so conflated, the caching may just be better there anyways. It also would be unlikely to have the `if` guards on every single line in the script since the WASM, style, and clippy checks would each have their own job sections. Thoughts on trying Cirrus CI out? GitHub Actions also exists these days, but 2000 minutes may burn quickly on this project without inter-build caching of some kind (currently planned, but not done yet). Or maybe just ditching the Rust "template" stuff Travis has which seems…unfortunately slow.

**Comment by mathstuf** [comment]
So taking into account the staggering that happened here, this took about 23 minutes wall clock time to complete which is a little over half the old wall clock time. There should be some overlap possible between concurrent PRs as well since rustfmt and WASM seem to be faster now (though the wasm-bindgen-cli build time is still ridiculous and 80+% of that job's time).

I suspect the #277 problem with nightly was a busted cache tarball taking 10+ minutes to extract and Travis killing it when the extraction wasn't verbose. I don't know if there's some way you can dump that cache bundle from an admin panel or something on the site if something like that happens again.

**Comment by mathstuf** [comment]
So this is *much* faster than before. Another 50% or so wall-clock time improvement, so it's around 10 minutes now.

But, something changed somewhere that isn't downcasing all of the member fields properly. Time to go through dependencies and find the culprit…

**Comment by mathstuf** [comment]
OK, let's see what kinds of times we can get now that this is based on #284.

**Comment by mathstuf** [comment]
Whew! All builds are under 10 minutes…except WASM which spends most of that time building `wasm-bindgen-cli`. Finding a way to cache that tool build is the next lowest-hanging fruit.

**Comment by tomhoule** [comment]
Awesome!

For wasm-bindgen-cli, there are binary releases here: https://github.com/rustwasm/wasm-bindgen/releases - maybe we could use that? (let's keep it for a separate PR if it's too much to take on in this one)

**Comment by mathstuf** [comment]
Ooh, that would help a lot. I'd rather see it be faster here in one fell swoop :) . Update incoming shortly.

**Comment by mathstuf** [comment]
Well, it seems to be around 9.5 minutes now. About 6 minutes of cache manipulation for the main builders which is…ridiculous IMO. But investigating other CI can be done in #282.

**Pull request merged**
