### PR TITLE
[WIP] [web] Replace custom HTTP client with external crate

### PR DESCRIPTION
**Pull request by tomhoule**
This simplifies things a lot, and we benefit from other people's work on HTTP in the browser.

Current status: the web example works.

### CODE REVIEW

**Comment by kellpossible** [comment]
I noticed reqwest is missing a number of features for its wasm implementation, this won't affect this implementation will it?

**Comment by kellpossible** [comment]
reqwest also appears to bring in quite a few more dependencies

**Comment by tomhoule** [comment]
The main reason behind this is that there isn't a lot of active contributions to this crate, so I'd like to avoid having the maintenance burden of a custom HTTP client for the browser, so we can focus the little time we have on more graphql-related problems.

**Comment by kellpossible** [comment]
@tomhoule sounds reasonable, thanks for the reply!

**Comment by MidasLamb** [comment]
For me this branch seems to work (for wasm target). Could I help with this PR to get it through CI?

**Comment by Type1J** [comment]
How's this PR going? Any help needed?

**Comment by MidasLamb** [comment]
@Type1J , I think the maintainer is quite busy at the moment. I've created #338 which should help this along.

**Comment by tomhoule** [comment]
I'm indeed very busy, but I'm not the only maintainer and I am happy to review pull requests :) I hope I'll find a few hours for graphql-client next month.

**Comment by tomhoule** [comment]
I just noticed #338  is no longer WIP - I'll find time to review it soon. If not feel free to ping me.

**Pull request closed without merging**
